version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
    container_name: mi_webapp_container
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy_container
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx_config/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
